### ISSUE TITLE
Sorting Order

### ISSUE THREAD

**Issue by nohimx** [billmurrin/graylog-plugin-slookup-function#1]
Hello. There is small issue with slookup. If there few records with same value, slookup using first one from current sorting. Any new values arrived to graylog lookup doesn't see, it only see first found. Is it possible to add sort ordering to slookup function, to be something like slookup(stream, srcField, dstField, rtnField, timeRange, sortOrder) : String  
SortOrder - asc , desc. Or even make sort desc by default, to find latest value. I am absolutely dumb in Java and cant do myself :(

**Comment by billmurrin** [comment]
Hi @nohimx.

Thanks for the input. I think I can definitely add this for you. 

Let's add an enhancement label to this! :-) 

I like the idea of adding a sortOrder since people might have different requirements when using the plugin.

**Comment by billmurrin** [comment]
@nohimx - [v1.1.0](https://github.com/billmurrin/graylog-plugin-slookup-function/releases/tag/v1.1.0) was just released which incorporates this enhancement. Please take it for a spin. It should work in all 2.2.X versions. I tested it in 2.2.1 and 2.2.3.
