### ISSUE TITLE
Searching in fields containing colons (eg. MacAddress)

### ISSUE THREAD

**Issue by Tomaszek77** [billmurrin/graylog-plugin-slookup-function#6]
If I search for fields which contain values like MacAddresses, slookup throws an error:

```
In call to function 'slookup' at 5:17 an exception was thrown: Unable to perform search query.
Failed to parse query [MACAddress:ee:db:65:xx:xx:xx]Failed to parse query [MACAddress:ee:db:65:xx:xx:xx]
```
I think there is no quoting special characters in slookup (?).

**Comment by billmurrin** [comment]
@Tomaszek77 - I've added some escape code to the develop branch to escape Lucene characters. Conducting some final testing. Version 2.0.0 should come out tomorrow or Wednesday. Thanks for your patience.

**Comment by billmurrin** [comment]
Looks like this is fixed in the latest version.
